# Generated by Django 6.1.1 on 2026-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('person_type', models.CharField(choices=[('entrepreneur', 'Entrepreneur / Business Owner'), ('student', 'Student'), ('job_seeker', 'Job Seeker'), ('training_partner', 'Training Partner'), ('investor', 'Investor'), ('media_guest', 'Media / Podcast Guest'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
