# Generated by Django 6.1.1 on 2026-09-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('contact_us', 'Contact Us'), ('partner_with_us', 'Partner With Us'), ('book_consultation', 'Book a Consultation'), ('join_training', 'Join a Training Program')], default='contact_us', max_length=30),
        ),
    ]
