# Generated by Django 6.1.1 on 2026-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='featured_work/')),
                ('metric_value', models.CharField(blank=True, max_length=100)),
                ('metric_label', models.CharField(blank=True, max_length=255)),
                ('secondary_metric_value', models.CharField(blank=True, max_length=100)),
                ('secondary_metric_label', models.CharField(blank=True, max_length=255)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
