# Generated by Django 6.1.1 on 2026-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredwork',
            name='media',
        ),
        migrations.AddField(
            model_name='featuredwork',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='featured-work/thumbnails/'),
        ),
        migrations.AddField(
            model_name='featuredwork',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
