# Generated by Django 6.1.1 on 2026-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='role_or_handle',
            new_name='handle',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
