# Generated by Django 6.1.1 on 2026-09-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='video_file',
        ),
    ]
