# Generated by Django 6.1.1 on 2026-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0002_remove_podcast_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='stats',
        ),
        migrations.AddField(
            model_name='podcast',
            name='metric_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='metric_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='supporting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
