# Generated by Django 6.1.1 on 2026-09-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('video', models.FileField(blank=True, null=True, upload_to='insights/videos/')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('featured', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('publish_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='insight_category.insightcategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
