# Generated by Django 6.1.1 on 2026-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_category', '0002_insight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='video',
        ),
        migrations.AddField(
            model_name='insight',
            name='card_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='card_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='metric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='metric_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='studio_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='insights/studio/'),
        ),
        migrations.AddField(
            model_name='insight',
            name='studio_thumbnail_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
