# Generated by Django 6.1.1 on 2026-09-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight_category', '0003_rename_image_insight_thumbnail_remove_insight_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='recommended',
        ),
    ]
